### ISSUE TITLE
fix osx time calculation

### ISSUE THREAD

**Issue by juliangruber** [juliangruber/travis-watch#11]
osx clocks seem to live in the future, showing values like `-12394s`

**Comment by neilstuartcraig** [comment]
Hi again.

Just thought i'd drop you a note in caae you didn't yet spot this...

I was running a test and saw that when the OSX builds are reporting -ve times, they're shown as "not started" in the Travis UI. This made me think that probably a quick(er) and reasonably legit fix might just be to treat -ve times in travis-watch the same way, i.e. not started.

Sketchy screenshot to illustrate:
<img width="903" alt="screen shot 2017-03-24 at 21 39 48" src="https://cloud.githubusercontent.com/assets/320215/24314706/ea62df72-10da-11e7-8d4a-00c34747e4bc.png">

The crossover point was perfect - when the travis UI marked the OSX tests as started, travis-watch started to count up from 0s.

Hope that makes sense.

Cheers

**Comment by juliangruber** [comment]
thanks! hopefully fixed in 1.12.2
