### ISSUE TITLE
TypeError: Invalid Version: node.0.0

### ISSUE THREAD

**Issue by neilstuartcraig** [juliangruber/travis-watch#13]
Hi

This project looks super cool & i'm really keen to try it but i'm getting errors. Here's what I did (as per readme):

```
npm i -g travis-watch

cd /path/to/proj
travis watch .
```

And i get an error:
```
travis-watch
⠸ Loading jobs/usr/local/lib/node_modules/travis-watch/node_modules/semver/semver.js:293
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: node.0.0
    at new SemVer (/usr/local/lib/node_modules/travis-watch/node_modules/semver/semver.js:293:11)
    at SemVer.compare (/usr/local/lib/node_modules/travis-watch/node_modules/semver/semver.js:342:13)
    at Function.compare (/usr/local/lib/node_modules/travis-watch/node_modules/semver/semver.js:566:31)
    at Object.keys.sort (/usr/local/lib/node_modules/travis-watch/index.js:68:21)
    at Array.sort (native)
    at Object.keys.forEach.os (/usr/local/lib/node_modules/travis-watch/index.js:67:47)
    at Array.forEach (native)
    at render (/usr/local/lib/node_modules/travis-watch/index.js:66:24)
    at check (/usr/local/lib/node_modules/travis-watch/index.js:135:11)
    at travis.jobs.get (/usr/local/lib/node_modules/travis-watch/index.js:55:5)
```

The project in question is [Stayck](https://github.com/neilstuartcraig/statyck) which i'm working on at the moment.

I assume TW is trying to read `version` from `package.json` - this is present in my `package.json`:

```
{
  "name": "statyck",
  "version": "1.2.0",
  "description": "A super simple, markdown-based, static blog generator",
  "main": "dist/bin.js",
  "bin": {
    "statyck": "dist/bin.js"
  },
  "config": {
    "force": true
  },
  "ava": {
    "require": [
      "babel-register"
    ],
    "babel": "inherit"
  },
  "scripts": {
...
```

My apologies if i am doing something stupid - I just can't see what :-).

More than happy to test/investigate/send a PR - is this something you can shortcut at all for me please?

Cheers

**Comment by neilstuartcraig** [comment]
Ah, maybe it's `engines`? Why did that only occur to me once i'd hit "Comment" :-). I'll check it.

**Comment by neilstuartcraig** [comment]
Nope, adding this didn't help:

```
...
"engines": 
  {
     "node" : ">=6.0.0" 
  },
...
```

Any pointers would be welcome.

**Comment by juliangruber** [comment]
ah, it's because of this: https://github.com/neilstuartcraig/statyck/blob/master/.travis.yml#L7 which then makes this fail https://github.com/juliangruber/travis-watch/blob/master/index.js#L68, which is used to sort the test results. sorting those special versions as "node" and "latest" last should do the trick.

i'll try to get a fix out tomorrow. thanks for reporting this :)

**Comment by neilstuartcraig** [comment]
Ah ha! I see, now you point that out it's obvious :-).

That'd be awesome. thanks. I seem to have a talent for doing things in a slightly awkward way :-).

**Comment by neilstuartcraig** [comment]
Confirm! This is fixed (and `travis-watch` is awesome - thank you @juliangruber :-))
