### ISSUE TITLE
Add support for Go

### ISSUE THREAD

**Issue by emersion** [juliangruber/travis-watch#24]

**Comment by juliangruber** [comment]
upgrade to latest:

```bash
$ npm install -g travis-watch@latest
```

and you get go support :)

![screen shot 2017-03-24 at 11 33 32](https://cloud.githubusercontent.com/assets/10247/24290583/c7f596e6-1085-11e7-9c34-37f64b494ab2.png)

![screen shot 2017-03-24 at 11 33 39](https://cloud.githubusercontent.com/assets/10247/24290587/ca7e165e-1085-11e7-89b9-2990dac5cd73.png)
