### ISSUE TITLE
RFC: 'open' command

### ISSUE THREAD

**Issue by amilajack** [juliangruber/travis-watch#32]
What are thoughts on a command that opens the current travis build? Similar to `hub`'s `browse` command

https://github.com/github/hub

**Comment by juliangruber** [comment]
interesting. what do you think about the printed out travis link in the results?

**Comment by amilajack** [comment]
In my opinion, I think opening the link might be a more elegant solution. It would be similar to the really nice `open` command OS X have: `open google.com` (opens google.com in default browser)

**Comment by juliangruber** [comment]
maybe instead the question to ask is why you want to open travis instead of looking at the cli?

**Comment by amilajack** [comment]
Its pretty common to quit the travis build, which can't be done with travis-watch.

**Comment by juliangruber** [comment]
i'm in favor of keeping this simple, you can still click on the printed out link in order to open the gui (command click in some terminals)
