### ISSUE TITLE
add logs command

### ISSUE THREAD

**Issue by juliangruber** [juliangruber/travis-watch#45]
either add to this or create a new tool.

This would stream travis log output from your selected build to the terminal.

**Comment by juliangruber** [comment]
maybe like this:

```bash
$ travis-watch logs

Build #806 datproject/dat-desktop #fix-integration-tests (10m)
https://travis-ci.org/datproject/dat-desktop/builds/227853750

linux
  [*] node_js: 7 DISPLAY=":99.0"

osx
  [ ] node_js: 7 DISPLAY=":99.0"
```

-> press `ENTER`

```bash
$ travis-watch logs

Build #806 datproject/dat-desktop #fix-integration-tests (10m)
https://travis-ci.org/datproject/dat-desktop/builds/227853750

linux node_js: 7 DISPLAY=":99.0"

LOG OUTPUT
```

**Comment by juliangruber** [comment]
i'm going to create this as a separate project first and then will see how it's best integrated

**Comment by aks-** [comment]
@juliangruber hey, have you already started working on this one? if not, is it okay for me to take a jab on it?

**Comment by juliangruber** [comment]
I forgot linking to the project :) https://github.com/juliangruber/travis-logs
