### ISSUE TITLE
Loading builds hangs

### ISSUE THREAD

**Issue by ralphtheninja** [juliangruber/travis-watch#47]
Just tried this out on `abstract-leveldown` but I can't seem to get any output.

Output:

```
lms@x240 ~/src/level/abstract-leveldown (TEST)
$ travis-watch 
⠹ Loading build
It is taking unusually long to fetch your build.
Have you pushed your commits yet?
```

**Comment by ralphtheninja** [comment]
Tried it on https://github.com/ralphtheninja/slump and then it works fine. Wondering what's the difference, or if there were just some random hickups with travis?

**Comment by juliangruber** [comment]
it works for me. have you pushed your most recent commit?

**Comment by juliangruber** [comment]
it looks like you're working in a TEST branch, is that public? just trying to reproduce

**Comment by ralphtheninja** [comment]
Yes I pushed it to the remote, but removed it now.

**Comment by juliangruber** [comment]
if you show me a commit where this hangs, i'll try to fix :)

**Comment by ralphtheninja** [comment]
We can merge https://github.com/Level/abstract-leveldown/pull/117 and try latest master

**Comment by ralphtheninja** [comment]
Checking https://travis-ci.org/Level/abstract-leveldown/builds/264412014 now (not yet started)

**Comment by ralphtheninja** [comment]
Now the travis build started and I get the same message. Not sure how to add more information to this. Maybe I should debug `travis-watch` locally.

**Comment by juliangruber** [comment]
hm, I was able look at the build from running travis-watch in the master branch. if you still see the same issue, yeah i guess local debugging would be nice :)

**Comment by ralphtheninja** [comment]
@juliangruber Aaaah, now I get what's going on. My workflow is pretty much always:

* fork repo A to my user -> B
* clone B
* setup `upstream` to A

So when using `travis-watch` it actually checks for `B` (I assume `origin` is involved somehow) and since I didn't have `ralphtheninja/abstract-leveldown` enabled on travis it doesn't work.

Makes sense?

**Comment by juliangruber** [comment]
ah! yes totally. hmm i haven't used it with this workflow yet. but also it wouldn't work, right, because there's no travis build running until you push it to some master

**Comment by ralphtheninja** [comment]
If I push to my forks master, there will be a build running for my fork, assuming I have enabled it on travis. So it does work, but picks my fork instead of the upstream in this case.

**Comment by ralphtheninja** [comment]
Anyway, I'm happy :)
