### ISSUE TITLE
Version requirement question

### ISSUE THREAD

**Issue by kiliankoe** [juliangruber/travis-watch#7]
Hi,

sorry for this issue having nothing to do whatsoever with this project (which looks pretty cool btw!). I'm just curious about something I spotted in your package.json and haven't seen elsewhere before. I'm sure there's a reason, I'm just curious why something like this is necessary. Thanks 😊 

```js
"devDependencies": {
    "prettier-standard-formatter": "^0.222222222222222.333333333333333"
},
```

**Comment by juliangruber** [comment]
To be quite honest I have no clue why this module uses versions like this. My guess is that it's for style or trolling!
